### ISSUE TITLE
"Best practices" badge is recognized as PNG

### ISSUE THREAD

**Issue by krlmlr** [r-dbi/r-dbi.org#1]
but comes as an SVG.

[![OpenSSF Best Practices](https://bestpractices.coreinfrastructure.org/projects/1882/badge)](https://bestpractices.coreinfrastructure.org/projects/1882)

https://github.com/cynkra/rdbidotorg/blob/887b3f4262d67f593f62ab8a2a94ba9db0cab21f/blog/posts/dbi-3-1.html#L192

Is there a way to fix this?

**Comment by maelle** [comment]
Taking notes from https://quarto.org/docs/websites/website-listings.html#listing-types

> The image for this item, read from the image field of the front matter, or automatically discovered by taking the first of an image of class preview-image, an image with a file name starting with feature, cover, or thumbnail, or the first image to appear in the document.

**Comment by maelle** [comment]
https://github.com/quarto-dev/quarto-cli/issues/6091

**Comment by maelle** [comment]
oh wait I fix the wrong problem!

**Comment by maelle** [comment]
https://github.com/quarto-dev/quarto-cli/issues/6092
