### ISSUE TITLE
Delete lines about GitHub projects

### ISSUE THREAD

**Issue by maelle** [r-dbi/r-dbi.org#10]
1. The projects are actually private.
2. New blog posts don't get projects anyway?
3. 
https://github.com/r-dbi/r-dbi.org/blob/50628f64f3e2db96963f4870d4f2be11b7e345e2/blog/posts/dbi-3-1.qmd#L240-L241

**Comment by krlmlr** [comment]
Remove the paragraph from the blog post?

**Comment by maelle** [comment]
Done in corresponding branch. Thank you!
