### ISSUE TITLE
Comments on latest blog post

### ISSUE THREAD

**Issue by maelle** [r-dbi/r-dbi.org#11]
I'm preparing a PR but here are other comments

- Why not split the post? I know it doubles as a report of activity, but it's very long. Each section could be a post.
- Could it be cross-posted on the cynkra blog?
- "DBI backens can now optionally support Arrow arrays and streams as the primary data exchange format." does not sound minor to me.
- In "DBItest: minor update to 1.8.1" the link to the bad tests article comes unannounced, could it be worked into the text a bit more.
- The RPostgres and RMariaDB sections are very cursory.

**Comment by krlmlr** [comment]
Handled, mostly. Thanks!
