### ISSUE TITLE
Fix homepage layout

### ISSUE THREAD

**Issue by krlmlr** [r-dbi/r-dbi.org#15]
On https://r-dbi.org/, I see when I scroll down:

![image](https://github.com/r-dbi/r-dbi.org/assets/1741643/4624266d-4384-43b4-8e62-c1cb22e00663)

**Comment by krlmlr** [comment]
What are these empty lines?

**Comment by maelle** [comment]
I think https://github.com/r-dbi/r-dbi.org/commit/f5e73a3eb6d71ff5c74f515a5c508a0911cd882c is the commit that fixed it.
