### ISSUE TITLE
Occasional hangs of `quarto render`

### ISSUE THREAD

**Issue by krlmlr** [r-dbi/r-dbi.org#16]
Observed on CI/CD, e.g., https://github.com/r-dbi/r-dbi.org/actions/runs/8587313662/job/23530803635#step:9:63, and locally. Any idea?

**Comment by maelle** [comment]
Locally I caught backends/index.qmd hanging :eyes:

**Comment by maelle** [comment]
Actually it hangs after that. Deleting blog/index.qmd removes the hanging so something is wrong with that file.

**Comment by maelle** [comment]
Not deleting blog/index.qmd, while deleting the draft post, also works.

**Comment by maelle** [comment]
It seems fixing the main index fixed this? Let's revisit if it happens again.
