### ISSUE TITLE
Enable GitHub Discussions for blog post

### ISSUE THREAD

**Issue by krlmlr** [r-dbi/r-dbi.org#20]
Discussions are on here: https://github.com/r-dbi/r-dbi.org/discussions .

**Comment by maelle** [comment]
it worked! https://r-dbi.org/blog/dbi-4-1/

**Comment by krlmlr** [comment]
Thanks, nice! No comments so far, AFAICT?

**Comment by maelle** [comment]
indeed, no comment so far
