### ISSUE TITLE
Noise in website builds

### ISSUE THREAD

**Issue by krlmlr** [r-dbi/r-dbi.org#4]
https://github.com/r-dbi/r-dbi.org/commit/3319c142beb8a037ac0d34df404e608e80f9fe03

@maelle: Can we use the "Git changed" date instead? An easy way to accomplish this is `git utimes` from git-extras: https://github.com/tj/git-extras/blob/main/Commands.md#git-utimes .

**Comment by maelle** [comment]
Exploring where that comes from 

https://github.com/quarto-dev/quarto-cli/blob/2da03b4b58d0d33b6a8e0a65cfb69d57ede273b3/src/resources/projects/website/listing/listing-default.ejs.md?plain=1#L3

leading to

https://github.com/quarto-dev/quarto-cli/blob/2da03b4b58d0d33b6a8e0a65cfb69d57ede273b3/src/resources/projects/website/listing/item-default.ejs.md?plain=1#L39

to be continued

**Comment by maelle** [comment]
maybe relevant https://github.com/quarto-dev/quarto-cli/blob/2da03b4b58d0d33b6a8e0a65cfb69d57ede273b3/src/project/types/website/listing/website-listing-template.ts#L457

**Comment by maelle** [comment]
let's use utimes :sweat_smile:

**Comment by maelle** [comment]
I had to build git-extras from source to get git-utimes.
