### ISSUE TITLE
how to replace db.rstudio.com/dbi

### ISSUE THREAD

**Issue by maelle** [r-dbi/r-dbi.org#9]
Broken link

https://github.com/r-dbi/r-dbi.org/blob/50628f64f3e2db96963f4870d4f2be11b7e345e2/blog/posts/dbi-3-1.qmd#L46

**Comment by krlmlr** [comment]
https://solutions.posit.co/connections/db/r-packages/dbi/ ?

**Comment by maelle** [comment]
thanks!
